#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint:fix && yarn type-check
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
